---
apiVersion: v1
kind: Secret
metadata:
  name: kibana-certs
  labels:
    app: elasticsearch
data:
  kibana-crt.pem: base64value
  kibana-key.pem: base64value
  kibana-root-ca.pem: base64value
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-rest-certs
  labels:
    app: elasticsearch
data:
  elk-rest-crt.pem: base64value
  elk-rest-key.pem: base64value
  elk-rest-root-ca.pem: base64value
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-transport-certs
  labels:
    app: elasticsearch
data:
  elk-transport-crt.pem:
  elk-transport-key.pem:
  elk-transport-root-ca.pem:
---
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-admin-certs
  labels:
    app: elasticsearch
data:
  admin-crt.pem:
  admin-key.pem:
  admin-root-ca.pem: